#!/usr/bin/env python3

with open('./i.txt') as f:
    lines = [int(line.rstrip()) for line in f]

jol = set(lines)

ma = max(jol)

check = 0

tab = []
tab.append(1)

for i in range(1, ma):
    if i not in jol:
        tab.append(0)
        continue

    tab.append(0)

    if (i-3) in jol:
        print("ASDF1")
        tab[i] += tab[i-3]

    if (i-2) in jol:
        print("ASDF2")
        tab[i] += tab[i-2]

    if (i-1) in jol:
        print("ASDF3")
        tab[i] += tab[i-1]

    print(tab)
